import { Button } from "@/components/ui/button";
import { FeatureMeta } from "@/components/site/FeatureMeta";
import { ArrowUpRight, BedDouble, Flame, Star, Users } from "lucide-react";
import Image from "next/image";
import type { StaticImageData } from "next/image";

type Accommodation = { title: string; image: string | StaticImageData; capacity: string; bed: string; amenity: string; price: string; badge: string };

export function AccommodationItem({ accommodation, night, cta }: { accommodation: Accommodation; night: string; cta: string }) {
  return <article className="group overflow-hidden rounded-[1.75rem] border border-[var(--line)] bg-white shadow-[0_10px_30px_rgba(18,37,28,.04)] transition-shadow duration-300 ease-out hover:shadow-[0_18px_42px_rgba(18,37,28,.12)]"><div className="relative aspect-[4/3] overflow-hidden"><Image src={accommodation.image} alt={accommodation.title} fill sizes="(min-width: 1280px) 33vw, (min-width: 768px) 50vw, 100vw" className="object-cover transition-transform duration-500 ease-out group-hover:scale-[1.02]" /><div className="absolute inset-x-0 bottom-0 h-1/3 bg-gradient-to-t from-black/30 to-transparent" /><span className="absolute left-4 top-4 rounded-lg bg-white/95 px-3 py-1.5 text-[11px] font-bold uppercase tracking-[.08em] text-[var(--forest)] shadow-sm">{accommodation.badge}</span></div><div className="p-6"><div className="flex items-start justify-between gap-3"><div><h3 className="font-heading text-[1.35rem] font-bold leading-tight tracking-[-.03em]">{accommodation.title}</h3><p className="mt-2 flex items-center gap-1.5 text-sm font-semibold text-[var(--text-secondary)]"><Star className="size-4 fill-[var(--warm-accent)] text-[var(--warm-accent)]" /> 4.9 <span className="font-normal text-[var(--text-muted)]">(128)</span></p></div><p className="rounded-xl bg-[var(--surface-muted)] px-3 py-1.5 text-right text-xs font-medium text-[var(--text-secondary)]"><strong className="block font-heading text-lg leading-none text-[var(--text-primary)]">{accommodation.price}</strong><span className="mt-1 block">{night}</span></p></div><div className="mt-5 flex flex-wrap gap-x-4 gap-y-2"><FeatureMeta icon={Users}>{accommodation.capacity}</FeatureMeta><FeatureMeta icon={BedDouble}>{accommodation.bed}</FeatureMeta><FeatureMeta icon={Flame}>{accommodation.amenity}</FeatureMeta></div><Button className="mt-6 flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-[var(--forest)] text-sm font-bold text-white transition hover:bg-[var(--forest-hover)]">{cta}<ArrowUpRight className="size-4" /></Button></div></article>;
}
