export type Locale = "vi" | "en";

export const content = {
  vi: {
    nav: ["Trang chủ", "Lưu trú", "Trải nghiệm", "Cẩm nang", "Thư viện"],
    login: "Đăng nhập", book: "Đặt chỗ", hero: "Ngủ dưới trời sao.\nThức dậy giữa Đà Lạt.",
    heroText: "Những khu cắm trại, glamping và trải nghiệm ngoài trời đáng nhớ giữa rừng thông Đà Lạt.",
    explore: "Khám phá chỗ ở", watch: "Xem trải nghiệm", filter: "Tìm chỗ ở",
    checkIn: "Ngày nhận phòng", checkOut: "Ngày trả phòng", guests: "Khách", stayType: "Loại lưu trú", selectDate: "Chọn ngày", summary: "Chọn ngày • 1 khách • Lều trại",
    home: {
      stays: { eyebrow: "Khám phá chốn nghỉ", title: "Ở Đà Lạt theo cách của bạn", description: "Từ lều dưới rừng thông đến cabin ấm áp, chọn một cuối tuần thật chậm.", items: [["Lều giữa rừng thông", "Khoảng riêng để nghe gió và ngắm sương Đà Lạt.", "50 bãi trống"], ["RV & Caravan", "Dễ đến, tiện nghi chu đáo và tầm nhìn rộng mở.", "25 chỗ caravan"], ["Glamping", "Ga giường êm, bếp lửa riêng và bầu trời đầy sao.", "10 lều chuông"], ["Cabin", "Chốn nghỉ ấm áp, yên tĩnh giữa thiên nhiên.", "10 cabin"]] },
      activities: { eyebrow: "Trải nghiệm", title: "Không chỉ là một kỳ nghỉ", description: "Đi xa hơn trên những cung đường cao nguyên, chèo chậm hơn và trở về bên bếp lửa đang ấm.", imageAlt: "Bạn bè quây quần bên lửa trại ở Đà Lạt", items: [["Đi bộ đường mòn", "Những cung đường cho mọi nhịp bước."], ["Chèo thuyền", "Thong thả trên mặt hồ Tuyền Lâm."], ["Lửa trại", "Buổi tối chậm rãi bên ánh lửa."], ["Khám phá thiên nhiên", "Rừng thông là người bạn cạnh bên."], ["Ngắm sao", "Trời cao nguyên trong hơn, đêm sáng hơn."], ["Đạp xe", "Khám phá những con dốc quanh trại."]] },
      booking: { eyebrow: "Chỗ ở nổi bật", title: "Tìm chốn nghỉ phù hợp", description: "Những không gian được chuẩn bị để bạn tạm rời nhịp vội, an trú và thức dậy gần thiên nhiên.", night: "/ đêm", cta: "Xem chỗ ở", items: [["Lều chuông Thông Xanh", "Tối ưu cho nhóm bạn", "Tối đa 4 khách", "Giường queen", "Bếp lửa riêng"], ["Lều ven hồ Tuyền Lâm", "Phù hợp gia đình", "Tối đa 6 khách", "2 giường đôi", "Sàn ngắm hồ"], ["Cabin Sương Mai", "Dành cho hai người", "Tối đa 2 khách", "Giường king", "Lò sưởi củi"]] },
      benefits: { eyebrow: "Vì sao chọn Camp Haven", title: "Đủ tiện nghi. Vẫn thật gần thiên nhiên.", items: [["Vị trí giữa thiên nhiên", "Những nơi đẹp được gìn giữ cẩn thận."], ["Riêng tư và yên tĩnh", "Khoảng không để bạn trở về nhịp riêng."], ["Tiện nghi hiện đại", "Vừa đủ để ở ngoài trời vẫn thật thoải mái."], ["Thân thiện với gia đình", "Kỷ niệm ngoài trời cho mọi lứa tuổi."], ["Chào đón thú cưng", "Đưa người bạn đồng hành lên đường mòn."], ["Đặt chỗ dễ dàng", "Lên kế hoạch cho chuyến đi chỉ trong vài bước."]] },
      testimonials: { eyebrow: "Chia sẻ từ khách", title: "Được yêu mến bởi những người mê cuối tuần", items: [["Một cuối tuần thật sự được nạp lại năng lượng. Không gian đẹp, tiện nghi sạch sẽ và hoàng hôn tuyệt vời.", "Emma & Jack", "Chuyến đi cuối tuần"], ["Hoang sơ vừa đủ nhưng mọi chi tiết đều khiến chúng tôi thấy thư giãn.", "Maya Nguyen", "Chuyến đi cùng bạn bè"], ["Bọn trẻ ở ngoài trời cả ngày và chúng tôi thật sự được nghỉ ngơi. Chắc chắn sẽ quay lại.", "Gia đình Parkers", "Chuyến đi gia đình"]] },
      news: { eyebrow: "Cẩm nang", title: "Những câu chuyện ngoài trời", all: "Xem tất cả bài viết →", read: "Đọc bài viết", excerpt: "Gợi ý nhỏ để cuối tuần của bạn có thêm khoảng thở.", imageAlt: "Cẩm nang trải nghiệm Đà Lạt", items: [["Cẩm nang cắm trại", "Lên kế hoạch một cuối tuần thật sự được nghỉ", "24/05/2026"], ["Ghi chép đường rừng", "Khám phá rừng thông theo một nhịp chậm hơn", "12/05/2026"], ["Bếp lửa ngoài trời", "Ba món đơn giản đáng nấu khi đi cắm trại", "28/04/2026"]] },
      gallery: { eyebrow: "Nhật ký cắm trại", title: "Khoảnh khắc ở trại", description: "Những điều nhỏ bé, bầu trời rộng lớn và chẳng cần vội đi đâu.", cta: "Xem thư viện →", imageAlt: "Khoảnh khắc cắm trại ở Đà Lạt" },
      cta: { eyebrow: "Hít thở giữa thiên nhiên", title: "Chuyến đi tiếp theo gần hơn bạn nghĩ.", description: "Chậm lại, bước ra ngoài và biến cuối tuần tới thành một kỷ niệm đáng nhớ.", stay: "Tìm chỗ ở", activities: "Khám phá trải nghiệm" },
      footer: { description: "Những chốn nghỉ chu đáo cho người thấy dễ chịu hơn khi ở ngoài trời.", explore: "Khám phá", information: "Thông tin", follow: "Theo dõi", stays: "Lưu trú", activities: "Trải nghiệm", gallery: "Thư viện", journal: "Cẩm nang", about: "Về chúng tôi", policies: "Chính sách", contact: "Liên hệ", subscribe: "Đăng ký", placeholder: "Nhận cảm hứng cho chuyến đi tiếp theo", copyright: "© 2026 Camp Haven. Bảo lưu mọi quyền." },
    },
  },
  en: {
    nav: ["Home", "Stays", "Activities", "Journal", "Gallery"], login: "Login", book: "Book your stay", hero: "Sleep Under the Stars.\nWake Up in Da Lat.",
    heroText: "Thoughtful campsites, glamping stays and outdoor moments among Da Lat’s pine forests.", explore: "Explore stays", watch: "Watch experience", filter: "Search stays",
    checkIn: "Check in", checkOut: "Check out", guests: "Guests", stayType: "Stay type", selectDate: "Select date", summary: "Select dates • 1 guest • Tent site",
    home: {
      stays: { eyebrow: "Find your stay", title: "Experience Da Lat your way", description: "From tents under pine trees to warm cabins, choose a weekend at your own pace.", items: [["Pine forest tent", "A private place for listening to the wind and watching Da Lat's mist.", "50 open sites"], ["RV & Caravan", "Easy arrivals, thoughtful facilities and wide-open views.", "25 caravan sites"], ["Glamping", "Soft sheets, private firepits and starry skies.", "10 bell tents"], ["Cabins", "A warm, quiet basecamp in the heart of nature.", "10 cabins"]] },
      activities: { eyebrow: "Activities", title: "More than a stay", description: "Follow the highland trails, paddle slowly and return to a glowing fire.", imageAlt: "Friends around a Da Lat campfire", items: [["Hiking", "Trails for every pace."], ["Kayaking", "Paddle slowly on Tuyen Lam Lake."], ["Bonfire", "Slow evenings by the fire."], ["Nature walks", "The pine forest is your neighbour."], ["Stargazing", "Clearer highland skies, brighter nights."], ["Cycling", "Explore the hills around camp."]] },
      booking: { eyebrow: "Featured stays", title: "Find your perfect basecamp", description: "Thoughtfully prepared spaces to unplug, settle in and wake up close to nature.", night: "/ night", cta: "View stay", items: [["Pine Bell Tent", "Best for friends", "Up to 4 guests", "Queen bed", "Private firepit"], ["Tuyen Lam Lake Tent", "Family favourite", "Up to 6 guests", "2 double beds", "Lake-view deck"], ["Morning Mist Cabin", "Best for couples", "Up to 2 guests", "King bed", "Wood stove"]] },
      benefits: { eyebrow: "Why Camp Haven", title: "Everything you need. Nothing you don't.", items: [["Nature-first locations", "Beautiful places, thoughtfully kept."], ["Private & peaceful", "Space to settle into your own rhythm."], ["Modern facilities", "The comforts that make outdoor easy."], ["Family friendly", "Fresh-air memories for every age."], ["Pet friendly", "Bring your favourite trail buddy."], ["Easy online booking", "Plan the escape in just a few clicks."]] },
      testimonials: { eyebrow: "Guest notes", title: "Loved by weekend explorers", items: [["The perfect weekend reset. Beautiful location, clean facilities and the sunset was incredible.", "Emma & Jack", "Weekend getaway"], ["It felt wild in all the right ways, but the details made it genuinely relaxing.", "Maya Nguyen", "Friends' escape"], ["The kids were outside all day and we actually switched off. We'll be back.", "The Parkers", "Family adventure"]] },
      news: { eyebrow: "Journal", title: "Stories from the outdoors", all: "Read all stories →", read: "Read story", excerpt: "Simple notes for making more room in your weekend.", imageAlt: "Da Lat outdoor journal", items: [["Camp guides", "How to plan a weekend that actually feels like a break", "May 24, 2026"], ["Field notes", "A slower way to explore the pine forest", "May 12, 2026"], ["Campfire food", "Three easy meals worth cooking outside", "April 28, 2026"]] },
      gallery: { eyebrow: "The camp journal", title: "Life at camp", description: "Small moments, big skies and no rush to be anywhere else.", cta: "View gallery →", imageAlt: "Camping moments in Da Lat" },
      cta: { eyebrow: "Take a breath outside", title: "Your next escape is closer than you think.", description: "Slow down, step outside and make your next weekend unforgettable.", stay: "Find your stay", activities: "Explore activities" },
      footer: { description: "Thoughtful stays for people who feel better outside.", explore: "Explore", information: "Information", follow: "Follow", stays: "Stays", activities: "Activities", gallery: "Gallery", journal: "Journal", about: "About", policies: "Policies", contact: "Contact", subscribe: "Subscribe", placeholder: "Get outdoor inspiration in your inbox", copyright: "© 2026 Camp Haven. All rights reserved." },
    },
  },
} as const;
