"use client";
import { ArrowUpRight } from "lucide-react";
import Image from "next/image";
import { SectionHeading } from "@/components/site/SectionHeading";
import { useLanguage } from "@/components/i18n/LanguageProvider";
import ForestPath from "@/public/assets/pexels-quachtungduong-34668894.webp";
import MountainLake from "@/public/assets/pexels-nguyndoanfoto-38435448.webp";
import WoodlandCampfire from "@/public/assets/pexels-pixelman-dapha-2147725010-30563254.webp";

const photos = [MountainLake, ForestPath, WoodlandCampfire];

export default function News() { const { t } = useLanguage(); const { news } = t.home; return <section id="news" className="section-space bg-[var(--warm-ivory)]"><div className="page-shell"><div className="flex flex-wrap items-end justify-between gap-5"><SectionHeading eyebrow={news.eyebrow} title={news.title} /><a href="#" className="inline-flex items-center gap-1 text-sm font-bold text-[var(--forest)] transition hover:text-[var(--forest-hover)]">{news.all}<ArrowUpRight className="size-4" /></a></div><div className="mt-10 grid gap-5 lg:grid-cols-[1.05fr_.95fr]">{news.items.map(([category, title, date], index) => <article key={title} className={`group overflow-hidden rounded-[1.75rem] border border-black/[.04] bg-white ${index === 0 ? "lg:row-span-2" : "lg:grid lg:grid-cols-[minmax(0,.9fr)_minmax(0,1.1fr)]"}`}><div className={`relative min-w-0 overflow-hidden ${index === 0 ? "aspect-[16/11]" : "aspect-[16/10] lg:h-full lg:aspect-auto"}`}><Image src={photos[index]} alt={news.imageAlt} fill sizes={index === 0 ? "(min-width: 1024px) 52vw, 100vw" : "(min-width: 1024px) 25vw, 100vw"} className="object-cover transition duration-700 group-hover:scale-[1.04]" /></div><div className={`flex min-w-0 flex-col p-6 ${index === 0 ? "md:p-7" : "lg:p-6"}`}><p className="text-[11px] font-bold uppercase tracking-[.14em] text-[var(--forest)]">{category} <span className="ml-2 text-[var(--text-muted)]">{date}</span></p><h3 className={`mt-3 font-heading font-bold leading-[1.15] tracking-[-.03em] ${index === 0 ? "text-2xl md:text-[1.7rem]" : "text-xl"}`}>{title}</h3><p className="mt-3 text-sm leading-6 text-[var(--text-secondary)]">{news.excerpt}</p><a href="#" className="mt-6 inline-flex items-center gap-1.5 text-sm font-bold text-[var(--forest)]">{news.read}<ArrowUpRight className="size-4 transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></a></div></article>)}</div></div></section>; }
