"use client";
import { Button } from "@/components/ui/button";
import { Calendar } from "@/components/ui/calendar";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useLanguage } from "@/components/i18n/LanguageProvider";
import { format } from "date-fns";
import { CalendarIcon, Search, Tent, Users, X } from "lucide-react";
import { useState } from "react";

export function BookingForm() {
  const { t } = useLanguage(); const [open, setOpen] = useState(false); const [checkIn, setCheckIn] = useState<Date>(); const [checkOut, setCheckOut] = useState<Date>();
  const fields = <div className="grid gap-3 lg:grid-cols-[repeat(4,minmax(0,1fr))_auto] lg:items-stretch lg:gap-0 lg:divide-x lg:divide-[var(--line)]"><Date label={t.checkIn} placeholder={t.selectDate} date={checkIn} setDate={setCheckIn} /><Date label={t.checkOut} placeholder={t.selectDate} date={checkOut} setDate={setCheckOut} /><Field icon={<Users />} label={t.guests}><Select defaultValue="1"><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="1">1 {t.guests.toLowerCase()}</SelectItem><SelectItem value="2">2 {t.guests.toLowerCase()}</SelectItem></SelectContent></Select></Field><Field icon={<Tent />} label={t.stayType}><Select defaultValue="tent"><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="tent">{t.tent}</SelectItem><SelectItem value="glamping">{t.glamping}</SelectItem><SelectItem value="cabin">{t.cabin}</SelectItem></SelectContent></Select></Field><Button className="h-12 rounded-xl bg-[var(--forest)] px-5 text-white hover:bg-[var(--forest-hover)] lg:my-2 lg:mr-2"><Search className="size-4" /> {t.filter}</Button></div>;
  return <div id="booking" className="absolute inset-x-0 bottom-0 z-20 translate-y-1/2 px-4 md:px-8"><div className="mx-auto max-w-[1240px] rounded-2xl border border-white/60 bg-white/95 p-2 shadow-[0_16px_40px_rgba(18,37,28,.18)] backdrop-blur"><button onClick={()=>setOpen(true)} className="flex h-14 w-full items-center justify-between rounded-xl bg-[var(--surface-muted)] px-5 text-left text-sm font-bold text-[var(--text-primary)] lg:hidden"><span>{t.summary}</span><span className="grid size-9 place-items-center rounded-lg bg-[var(--forest)] text-white"><Search className="size-4" /></span></button><div className="hidden lg:block">{fields}</div></div>{open && <div className="fixed inset-0 z-[70] flex items-end bg-black/45 p-3 lg:hidden"><div className="max-h-[78dvh] w-full overflow-hidden rounded-[2rem] bg-white shadow-2xl"><div className="mx-auto mt-3 h-1 w-10 rounded-full bg-[var(--line)]" /><div className="flex items-center justify-between px-5 pb-4 pt-3"><b className="font-heading text-lg">{t.filter}</b><button onClick={()=>setOpen(false)} aria-label="Close booking form" className="grid size-9 place-items-center rounded-full bg-[var(--surface-muted)]"><X className="size-5" /></button></div><div className="overflow-y-auto px-5 pb-6">{fields}</div></div></div>}</div>;
}
function Field({icon,label,children}:{icon:React.ReactNode;label:string;children:React.ReactNode}){return <div className="rounded-2xl border border-[var(--line)] p-4 lg:rounded-none lg:border-0 lg:px-5 lg:py-4"><p className="mb-2 flex items-center gap-2 text-xs font-medium text-[var(--text-secondary)]">{icon}{label}</p>{children}</div>}
function Date({label,placeholder,date,setDate}:{label:string;placeholder:string;date?:Date;setDate:(d?:Date)=>void}){return <Field icon={<CalendarIcon />} label={label}><Popover><PopoverTrigger asChild><Button variant="ghost" className="w-full justify-start p-0">{date?format(date,"dd/MM/yyyy"):placeholder}</Button></PopoverTrigger><PopoverContent><Calendar mode="single" selected={date} onSelect={setDate}/></PopoverContent></Popover></Field>}
